[workspace]
members = [
    "admin",
    "cargo-audit",
    "cargo-lock",
    "cvss",
    "platforms",
    "platforms/markdown-table-gen",
    "rustsec"
]

[patch.crates-io]
semver = { git = 'https://github.com/Shnatsel/semver.git' }
