[package]
name        = "platforms"
description = """
Rust platform registry with information about valid Rust platforms (target
triple, target_arch, target_os) sourced from the Rust compiler.
"""
version    = "3.0.0-alpha.1" # Also update html_root_url in lib.rs when bumping this
authors    = ["Tony Arcieri <bascule@gmail.com>"]
license    = "Apache-2.0 OR MIT"
homepage   = "https://rustsec.org"
repository = "https://github.com/rustsec/rustsec/tree/main/platforms"
readme     = "README.md"
categories = ["development-tools", "no-std"]
keywords   = ["architectures", "cpu", "platforms", "os", "targets"]
edition    = "2018"

[dependencies]
serde = { version = "1", optional = true }

[features]
default = ["std"]
std = []
