name: cargo-audit

on:
  pull_request:
    paths:
      - ".github/workflows/cargo-audit.yml"
      - "cargo-audit/**"
      - "rustsec/**"
      - "Cargo.*"
  push:
    branches: main

defaults:
  run:
    working-directory: cargo-audit

env:
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check

  # TODO(tarcieri): re-unify build matrix when platform-specific problems are fixed
  test:
    strategy:
      matrix:
        toolchain:
          - stable # MSRV is enforced by the 'workspace' job
        runs-on:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          profile: minimal
          override: true
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --all-features

  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.74.0
          override: true
          profile: minimal
      - uses: Swatinem/rust-cache@v2
      - run: cargo doc --all-features

# TODO(tarcieri): re-enable after vulnerable deps have been upgraded
#  self-audit:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions-rs/toolchain@v1
#        with:
#          toolchain: stable
#          profile: minimal
#          override: true
#      - name: Run cargo audit
#        run: cargo run -- audit
