name: Release

on:
  push:
    tags:
      - v*.*.*

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -D warnings

jobs:
  build:
    strategy:
      matrix:
        name:
          - linux-x86-64-gnu
          - linux-x86-64-musl
          - linux-armv7-gnu
          - linux-arm64-gnu
          - mac-x86-64
          - windows-x86-64
        include:
          - name: linux-x86-64-gnu
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            cross: false

          - name: linux-x86-64-musl
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            cross: true

          - name: linux-armv7-gnu
            os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            cross: true

          - name: linux-arm64-gnu
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            cross: true

          - name: mac-x86-64
            os: macos-latest
            target: x86-64-apple-darwin
            cross: false

          - name: windows-x86-64
            os: windows-latest
            target: x86-64-pc-windows-msvc
            cross: false

    name: Binaries for ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('Cargo.lock') }}
      - uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('Cargo.lock') }}
      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          profile: minimal
          override: true
      - uses: actions-rs/cargo@v1.0.3
        name: Build
        with:
          use-cross: ${{ matrix.cross }}
          command: build
          args: --release --locked --features fix --target ${{ matrix.target }}
      - name: Package
        shell: bash
        run: |
          set -eux
          bin="target/${{ matrix.target }}/release/cargo-audit"
          version=$(echo "${{ github.ref }}" | cut -d/ -f3)
          dst="cargo-audit-${{ matrix.target }}-${version}"
          mkdir "$dst"
          mv "$bin" "$dst/"
          mv README.md CHANGELOG.md LICENSE-APACHE LICENSE-MIT "$dst/"
      - name: Archive (tar)
        if: '! startsWith(matrix.name, ''windows-'')'
        shell: bash
        run: |
          version=$(echo "${{ github.ref }}" | cut -d/ -f3)
          dst="cargo-audit-${{ matrix.target }}-${version}"
          tar cavf "$dst.tgz" "$dst"
      - name: Archive (zip)
        if: startsWith(matrix.name, 'windows-')
        shell: bash
        run: |
          version=$(echo "${{ github.ref }}" | cut -d/ -f3)
          dst="cargo-audit-${{ matrix.target }}-${version}"
          7z a "$dst.zip" "$dst"
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            cargo-audit-*.tar.gz
            cargo-audit-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
